name: Run Tests and Coverage
on:
  push:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Run tests and check coverage
        run: |
          npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
          if [ $? -ne 0 ]; then
            echo "Coverage threshold not met."
            exit 1
          fi
